import React, { useEffect, useState } from 'react';
import { Megaphone, X } from 'lucide-react';
import type { Campaign } from '../../types';
import { useAuth } from '../../auth/AuthContext';

const value = (campaign: Campaign, key: string, fallback = '') => typeof campaign.config[key] === 'string' ? campaign.config[key] as string : fallback;

export const CampaignInlineBanner: React.FC<{ campaign: Campaign; onNavigate: (target: string) => void }> = ({ campaign, onNavigate }) => {
  const target = value(campaign, 'primaryTarget', 'pricing');
  return <article className="rounded-3xl overflow-hidden bg-gradient-to-r from-indigo-700 to-violet-700 text-white grid md:grid-cols-2"><div className="p-7 sm:p-9 flex flex-col justify-center gap-3"><p className="text-xs font-black text-indigo-200">{campaign.internalName}</p><h2 className="text-2xl font-black">{campaign.publicTitle}</h2><p className="text-sm text-white/80 leading-7">{campaign.subtitle || campaign.description}</p><div><button type="button" onClick={() => onNavigate(target)} className="px-5 py-3 rounded-xl bg-white text-indigo-700 text-sm font-black">{value(campaign, 'primaryLabel', 'اعرف المزيد')}</button></div></div>{value(campaign, 'imageUrl') && <picture><source media="(max-width: 640px)" srcSet={value(campaign, 'mobileImageUrl', value(campaign, 'imageUrl'))} /><img src={value(campaign, 'imageUrl')} alt="" loading="lazy" className="w-full h-52 md:h-full object-cover" /></picture>}</article>;
};

export const CampaignSurfaces: React.FC<{ campaigns: Campaign[]; onNavigate: (target: string) => void }> = ({ campaigns, onNavigate }) => {
  const { session } = useAuth(); const [popup, setPopup] = useState<Campaign | null>(null); const [stickyVisible, setStickyVisible] = useState(true);
  const announcement = campaigns.find((campaign) => campaign.locations.includes('announcement_bar')); const sticky = campaigns.find((campaign) => campaign.locations.includes('sticky_mobile')); const popupCampaign = campaigns.find((campaign) => campaign.locations.includes('popup'));
  useEffect(() => { if (!popupCampaign) return undefined; const audience = value(popupCampaign, 'audience', 'all'); if (audience === 'anonymous' && session) return undefined; if (audience === 'logged_in' && !session) return undefined; const delay = Math.max(3000, Math.min(Number(popupCampaign.config.delayMs) || 5000, 30000)); const key = `english30:campaign-popup:${popupCampaign.id}`; const oncePerDays = Math.max(0, Number(popupCampaign.config.oncePerDays) || 0); const last = Number(localStorage.getItem(key) || 0); if (oncePerDays && Date.now() - last < oncePerDays * 86400000) return undefined; if (!oncePerDays && sessionStorage.getItem(key)) return undefined; const timer = window.setTimeout(() => { setPopup(popupCampaign); if (oncePerDays) localStorage.setItem(key, String(Date.now())); else sessionStorage.setItem(key, '1'); }, delay); return () => window.clearTimeout(timer); }, [popupCampaign, session]);
  const action = (campaign: Campaign) => { const target = value(campaign, 'primaryTarget', 'pricing'); if (/^https:\/\//i.test(target)) window.location.assign(target); else onNavigate(target); };
  return <>{announcement && <div className="rounded-2xl bg-indigo-950 text-white px-4 py-3 flex items-center justify-center gap-3 text-sm font-bold"><Megaphone className="w-4 h-4 text-amber-300" /><span>{announcement.publicTitle || announcement.subtitle}</span>{value(announcement,'couponCode') && <span className="rounded-lg bg-white/10 px-2 py-1 text-xs">كود: {value(announcement,'couponCode')}</span>}{value(announcement,'primaryLabel') && <button type="button" onClick={() => action(announcement)} className="underline underline-offset-4">{value(announcement,'primaryLabel')}</button>}</div>}{sticky && stickyVisible && <div className="fixed bottom-3 inset-x-3 z-50 md:hidden"><div className="rounded-2xl bg-slate-950 text-white shadow-2xl p-3 flex items-center gap-3"><div className="flex-1 min-w-0"><p className="text-xs font-black truncate">{sticky.publicTitle}</p><p className="text-[11px] text-slate-300 truncate">{sticky.subtitle}</p></div><button type="button" onClick={() => action(sticky)} className="px-3 py-2 rounded-xl bg-indigo-500 text-xs font-black">{value(sticky,'primaryLabel','اعرف المزيد')}</button><button type="button" aria-label="إغلاق" onClick={() => setStickyVisible(false)} className="p-1"><X className="w-4 h-4" /></button></div></div>}{popup && <div className="fixed inset-0 z-[110] bg-slate-950/65 p-4 flex items-center justify-center" role="dialog" aria-modal="true" aria-label={popup.publicTitle}><div className="w-full max-w-lg overflow-hidden rounded-3xl bg-white shadow-2xl relative"><button type="button" aria-label="إغلاق الإعلان" onClick={() => setPopup(null)} className="absolute top-3 left-3 z-10 p-2 rounded-full bg-white/90 text-slate-700"><X className="w-5 h-5" /></button>{value(popup,'imageUrl') && <img src={value(popup,'imageUrl')} alt="" className="w-full max-h-56 object-cover" />}<div className="p-7"><p className="text-xs font-black text-indigo-600">{popup.internalName}</p><h2 className="text-2xl font-black mt-2">{popup.publicTitle}</h2><p className="text-sm text-slate-600 leading-7 mt-2">{popup.subtitle || popup.description}</p><button type="button" onClick={() => action(popup)} className="mt-5 w-full rounded-xl bg-indigo-600 text-white py-3 font-black">{value(popup,'primaryLabel','ابدأ الآن')}</button></div></div></div>}</>;
};
