import React, { useEffect, useState } from 'react';
import { ArrowLeft, Award, BookOpen, CheckCircle2, ChevronLeft, ChevronRight, Clock3, ExternalLink, Play, ShieldCheck, Sparkles, Star, Target, Users } from 'lucide-react';
import type { Campaign, Course, HomepageSection, PlatformSettings, VisualAnimationPreset } from '../../types';

export interface HomepageRendererProps {
  section: HomepageSection;
  settings: PlatformSettings;
  courses: Course[];
  campaigns?: Campaign[];
  onNavigate: (target: string) => void;
  ownerEditEnabled?: boolean;
  onEdit?: (section: HomepageSection) => void;
}

const text = (config: Record<string, unknown>, key: string, fallback = '') => typeof config[key] === 'string' ? config[key] as string : fallback;
const bool = (config: Record<string, unknown>, key: string, fallback = false) => typeof config[key] === 'boolean' ? config[key] as boolean : fallback;
const number = (config: Record<string, unknown>, key: string, fallback = 0) => typeof config[key] === 'number' && Number.isFinite(config[key]) ? config[key] as number : fallback;
const strings = (config: Record<string, unknown>, key: string) => Array.isArray(config[key]) ? (config[key] as unknown[]).filter((item): item is string => typeof item === 'string') : [];
const objects = (config: Record<string, unknown>, key: string) => Array.isArray(config[key]) ? (config[key] as unknown[]).filter((item): item is Record<string, unknown> => Boolean(item && typeof item === 'object' && !Array.isArray(item))) : [];
const safeHref = (value: string) => /^https:\/\//i.test(value) || /^\//.test(value) || /^#/.test(value) ? value : '#';
const animationClass = (preset?: unknown) => {
  const allowed: VisualAnimationPreset[] = ['fade_in','fade_up','fade_down','slide_left','slide_right','zoom_subtle','staggered_cards','soft_parallax','marquee','count_up','gentle_float'];
  return typeof preset === 'string' && allowed.includes(preset as VisualAnimationPreset) ? `visual-anim visual-anim-${preset}` : '';
};

const usePrefersReducedMotion = () => {
  const [reduced, setReduced] = useState(false);
  useEffect(() => { const query = window.matchMedia('(prefers-reduced-motion: reduce)'); const update = () => setReduced(query.matches); update(); query.addEventListener?.('change', update); return () => query.removeEventListener?.('change', update); }, []);
  return reduced;
};

const CTA: React.FC<{ label?: string; target?: string; onNavigate: (target: string) => void; secondary?: boolean }> = ({ label, target, onNavigate, secondary }) => label ? <button type="button" onClick={() => onNavigate(target || '#')} className={`inline-flex items-center justify-center gap-2 px-5 py-3 rounded-xl font-black text-sm transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-600 ${secondary ? 'border border-slate-200 bg-white/80 text-slate-700 hover:bg-white' : 'bg-indigo-600 text-white shadow-lg shadow-indigo-200 hover:bg-indigo-700'}`}>{label}<ArrowLeft className="w-4 h-4" /></button> : null;

const Countdown: React.FC<{ target?: string }> = ({ target }) => {
  const [remaining, setRemaining] = useState(() => Math.max(0, new Date(target || 0).getTime() - Date.now()));
  useEffect(() => { const timer = window.setInterval(() => setRemaining(Math.max(0, new Date(target || 0).getTime() - Date.now())), 1000); return () => window.clearInterval(timer); }, [target]);
  if (!target || remaining <= 0) return null;
  const totalSeconds = Math.floor(remaining / 1000); const days = Math.floor(totalSeconds / 86400); const hours = Math.floor(totalSeconds / 3600) % 24; const minutes = Math.floor(totalSeconds / 60) % 60; const seconds = totalSeconds % 60;
  return <div className="flex flex-wrap gap-2" aria-label="الوقت المتبقي"><span className="countdown-unit"><strong>{days}</strong><small>يوم</small></span><span className="countdown-unit"><strong>{String(hours).padStart(2,'0')}</strong><small>ساعة</small></span><span className="countdown-unit"><strong>{String(minutes).padStart(2,'0')}</strong><small>دقيقة</small></span><span className="countdown-unit"><strong>{String(seconds).padStart(2,'0')}</strong><small>ثانية</small></span></div>;
};

const Carousel: React.FC<{ items: Record<string, unknown>[]; autoplay?: boolean; interval?: number; render: (item: Record<string, unknown>, index: number) => React.ReactNode; label: string }> = ({ items, autoplay = false, interval = 7000, render, label }) => {
  const [active, setActive] = useState(0); const [paused, setPaused] = useState(false); const reduced = usePrefersReducedMotion(); const safeInterval = Math.max(5000, Math.min(interval, 15000));
  useEffect(() => { if (!autoplay || reduced || paused || items.length < 2) return undefined; const timer = window.setInterval(() => setActive((value) => (value + 1) % items.length), safeInterval); return () => window.clearInterval(timer); }, [autoplay, paused, reduced, safeInterval, items.length]);
  if (!items.length) return null;
  return <div className="relative" role="region" aria-roledescription="carousel" aria-label={label} onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)}>
    <div aria-live={autoplay && !reduced ? 'off' : 'polite'}>{render(items[active], active)}</div>
    {items.length > 1 && <><div className="absolute inset-y-0 inset-x-2 flex items-center justify-between pointer-events-none"><button type="button" aria-label="الشريحة السابقة" onClick={() => setActive((value) => (value - 1 + items.length) % items.length)} className="pointer-events-auto p-2 rounded-full bg-white/90 shadow text-slate-700 hover:text-indigo-600"><ChevronRight className="w-5 h-5" /></button><button type="button" aria-label="الشريحة التالية" onClick={() => setActive((value) => (value + 1) % items.length)} className="pointer-events-auto p-2 rounded-full bg-white/90 shadow text-slate-700 hover:text-indigo-600"><ChevronLeft className="w-5 h-5" /></button></div><div className="flex justify-center gap-1.5 mt-4">{items.map((_, index) => <button key={index} type="button" aria-label={`الشريحة ${index + 1}`} aria-current={index === active} onClick={() => setActive(index)} className={`h-2 rounded-full transition-all ${index === active ? 'w-6 bg-indigo-600' : 'w-2 bg-slate-300'}`} />)}</div></>}
  </div>;
};

const Hero: React.FC<HomepageRendererProps> = ({ section, settings, onNavigate, campaigns = [] }) => {
  const config = section.config; const campaign = campaigns[0]; const campaignConfig = campaign?.config ?? {}; const effective = campaign ? { ...config, ...campaignConfig, titleAr: campaign.publicTitle || text(config, 'titleAr'), subtitle: campaign.subtitle || text(config, 'subtitle'), showCountdown: true, countdownTarget: campaign.endAt } : config;
  const variant = text(effective, 'variant', 'gradient'); const slides = objects(effective, 'slides');
  const title = text(effective, 'titleAr', settings.heroHeadlineAr); const subtitle = text(effective, 'subtitle', settings.heroSubheadlineAr); const image = text(effective, 'imageUrl', settings.heroImageUrl); const mobileImage = text(effective, 'mobileImageUrl', image); const video = text(effective, 'videoUrl');
  const content = (slide: Record<string, unknown> = effective) => <div className={`relative z-10 max-w-3xl space-y-5 ${text(slide, 'align', text(effective, 'align', 'center')) === 'right' ? 'mr-0 ml-auto text-right' : text(slide, 'align', text(effective, 'align', 'center')) === 'left' ? 'ml-0 mr-auto text-left' : 'mx-auto text-center'}`}><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/15 border border-white/25 text-white text-xs font-black"><Sparkles className="w-4 h-4 text-amber-300" />{text(slide, 'badge', text(effective, 'badge', campaign ? campaign.internalName : settings.homepageBadgeAr))}</div><h1 className="text-3xl sm:text-5xl font-black leading-tight text-white">{text(slide, 'titleAr', title)}</h1>{text(slide, 'titleEn') && <p className="font-english text-lg text-white/80" dir="ltr">{text(slide, 'titleEn')}</p>}<p className="text-base sm:text-lg leading-8 text-white/85 max-w-2xl">{text(slide, 'subtitle', subtitle)}</p>{text(slide, 'trustLine') && <p className="text-sm text-white/75 flex items-center gap-2 justify-center"><ShieldCheck className="w-4 h-4" />{text(slide, 'trustLine')}</p>}<div className="flex flex-wrap gap-3 justify-center"><CTA label={text(slide, 'primaryLabel', settings.heroPrimaryCtaLabelAr)} target={text(slide, 'primaryTarget', settings.heroPrimaryCtaTarget)} onNavigate={onNavigate} /><CTA label={text(slide, 'secondaryLabel', settings.heroSecondaryCtaLabelAr)} target={text(slide, 'secondaryTarget', settings.heroSecondaryCtaTarget)} onNavigate={onNavigate} secondary /></div>{bool(slide, 'showCountdown', Boolean(campaign) || bool(effective, 'showCountdown')) && <Countdown target={text(slide, 'countdownTarget', text(effective, 'countdownTarget'))} />}</div>;
  const backdrop = image ? <><picture className="absolute inset-0"><source media="(max-width: 640px)" srcSet={mobileImage || image} /><img src={image} alt={text(effective, 'altText', '')} className="absolute inset-0 w-full h-full object-cover" fetchPriority="high" /></picture><div className="absolute inset-0 bg-slate-950/55" /></> : <div className={`absolute inset-0 ${text(effective, 'gradient', 'from-indigo-700 via-indigo-600 to-violet-700')} bg-gradient-to-br`} />;
  if (variant === 'split') return <section className="homepage-section overflow-hidden rounded-3xl bg-white border border-slate-200 shadow-sm"><div className="grid md:grid-cols-2 min-h-[420px]"><div className="p-7 sm:p-12 flex items-center bg-gradient-to-br from-indigo-700 to-violet-700">{content()}</div><div className="relative min-h-64 bg-slate-100">{image ? <img src={mobileImage || image} alt={text(config, 'altText', '')} className="absolute inset-0 w-full h-full object-cover" loading="eager" /> : <div className="absolute inset-0 flex items-center justify-center text-slate-400"><BookOpen className="w-16 h-16" /></div>}</div></div></section>;
  if (variant === 'video' && video) return <section className="homepage-section relative min-h-[440px] rounded-3xl overflow-hidden flex items-center p-7 sm:p-14">{backdrop}<video className="absolute inset-0 w-full h-full object-cover" autoPlay muted loop playsInline poster={image || undefined} aria-hidden="true"><source src={video} /></video><div className="absolute inset-0 bg-slate-950/50" />{content()}</section>;
  if ((variant === 'carousel' || slides.length > 0) && slides.length) return <section className="homepage-section relative overflow-hidden rounded-3xl min-h-[440px] flex items-center p-7 sm:p-14">{backdrop}<Carousel items={slides} autoplay={bool(config, 'autoplay', true)} interval={number(config, 'interval', 7000)} label="شرائح البطل" render={(slide) => content(slide)} /></section>;
  if (variant === 'text') return <section className="homepage-section rounded-3xl bg-white border p-8 sm:p-14"><div className="max-w-3xl mx-auto">{content()}</div></section>;
  return <section className={`homepage-section relative min-h-[${text(config, 'desktopHeight', '440px')}] rounded-3xl overflow-hidden flex items-center p-7 sm:p-14`}><div className="absolute inset-0">{image ? <picture><source media="(max-width: 640px)" srcSet={mobileImage || image} /><img src={image} alt={text(config, 'altText', '')} className="w-full h-full object-cover" fetchPriority="high" /></picture> : null}<div className={`absolute inset-0 ${image ? 'bg-slate-950/55' : 'bg-gradient-to-br from-indigo-700 via-indigo-600 to-violet-700'}`} /></div>{content()}</section>;
};

const CourseCard: React.FC<{ course: Course; onNavigate: (target: string) => void }> = ({ course, onNavigate }) => <article className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm hover:shadow-md transition"><div className="h-36 bg-slate-100">{course.image ? <img src={course.image} alt={course.titleAr} loading="lazy" className="w-full h-full object-cover" /> : <div className="h-full flex items-center justify-center text-indigo-300"><BookOpen className="w-10 h-10" /></div>}</div><div className="p-4 space-y-2"><div className="flex items-center justify-between gap-2"><span className="text-[10px] px-2 py-1 rounded-lg bg-indigo-50 text-indigo-700 font-black">{course.level}</span><span className="text-[11px] text-slate-500">{course.lessonsCount} درس</span></div><h3 className="font-black text-slate-900 line-clamp-2">{course.titleAr}</h3><p className="text-xs leading-6 text-slate-500 line-clamp-2">{course.descriptionAr}</p><button type="button" onClick={() => onNavigate(`course:${course.id}`)} className="text-indigo-700 text-xs font-black inline-flex items-center gap-1">استكشف الدورة <ArrowLeft className="w-3.5 h-3.5" /></button></div></article>;

export const HomepageSectionRenderer: React.FC<HomepageRendererProps> = (props) => {
  const { section, settings, courses, onNavigate, ownerEditEnabled, onEdit } = props; const c = section.config; const animation = animationClass(c.animation); const wrap = (child: React.ReactNode) => <section className={`${animation} relative ${ownerEditEnabled ? 'owner-homepage-editable' : ''}`} onClick={ownerEditEnabled ? (event) => { event.preventDefault(); event.stopPropagation(); onEdit?.(section); } : undefined}>{ownerEditEnabled && <button type="button" className="owner-section-edit" onClick={(event) => { event.stopPropagation(); onEdit?.(section); }}>تحرير القسم</button>}{child}</section>;
  if (section.sectionType === 'hero') return wrap(<Hero {...props} />);
  if (section.sectionType === 'announcement_bar') return wrap(<div className="rounded-2xl px-4 py-3 bg-indigo-950 text-white flex flex-wrap items-center justify-center gap-3 text-sm font-bold"><Sparkles className="w-4 h-4 text-amber-300" /><span>{text(c, 'text', settings.announcementBanner.textAr)}</span><CTA label={text(c, 'ctaLabel')} target={text(c, 'ctaTarget')} onNavigate={onNavigate} secondary /></div>);
  if (section.sectionType === 'promotional_banner' || section.sectionType === 'image_text_split') return wrap(<div className={`overflow-hidden rounded-3xl border bg-white grid md:grid-cols-2 ${section.sectionType === 'image_text_split' ? '' : 'md:grid-cols-[1.2fr_.8fr]'}`}><div className="p-7 sm:p-10 flex flex-col justify-center gap-4"><span className="text-xs font-black text-indigo-600">{text(c, 'badge', 'عرض خاص')}</span><h2 className="text-2xl sm:text-3xl font-black text-slate-900">{text(c, 'titleAr', 'طوّر لغتك الإنجليزية بخطوات واضحة')}</h2><p className="text-sm leading-7 text-slate-600">{text(c, 'description', 'تعلّم بطريقة منظمة تناسب وقتك ومستواك.')}</p><div><CTA label={text(c, 'ctaLabel', 'ابدأ الآن')} target={text(c, 'ctaTarget', 'courses')} onNavigate={onNavigate} /></div></div>{text(c, 'imageUrl') ? <img src={text(c, 'imageUrl')} alt={text(c, 'altText')} loading="lazy" className="w-full h-56 md:h-full object-cover" /> : <div className="min-h-56 bg-gradient-to-br from-indigo-100 to-violet-100 flex items-center justify-center text-indigo-500"><Sparkles className="w-14 h-14" /></div>}</div>);
  if (section.sectionType === 'image_carousel' || section.sectionType === 'testimonials' || section.sectionType === 'logos') { const items = objects(c, section.sectionType === 'image_carousel' ? 'slides' : 'items'); return wrap(<Carousel items={items} autoplay={bool(c, 'autoplay', false)} interval={number(c, 'interval', 7000)} label={section.sectionType === 'testimonials' ? 'آراء الطلاب' : 'معرض'} render={(item) => <div className="rounded-3xl bg-white border p-6 sm:p-8 min-h-44">{text(item, 'imageUrl') && <img src={text(item, 'imageUrl')} alt={text(item, 'altText')} loading="lazy" className="w-full max-h-72 object-cover rounded-2xl mb-4" />}{text(item, 'quote') && <p className="text-lg leading-8 text-slate-700">“{text(item, 'quote')}”</p>}{text(item, 'name') && <p className="mt-3 font-black text-indigo-700">{text(item, 'name')}</p>}{text(item, 'title') && <h2 className="text-2xl font-black">{text(item, 'title')}</h2>}</div>} />); }
  if (section.sectionType === 'featured_course' || section.sectionType === 'course_grid' || section.sectionType === 'course_carousel') { const selected = strings(c, 'courseIds'); const visible = selected.length ? courses.filter((course) => selected.includes(course.id)) : courses; const list = visible.slice(0, number(c, 'limit', section.sectionType === 'featured_course' ? 1 : 6)); return wrap(<div className="space-y-6"><div><span className="text-xs font-black text-indigo-600">{text(c, 'eyebrow', 'مسارك التعليمي')}</span><h2 className="text-2xl sm:text-3xl font-black text-slate-900">{text(c, 'titleAr', section.sectionType === 'featured_course' ? 'ابدأ بالدورة الأنسب لك' : 'دوراتنا المنشورة')}</h2>{text(c, 'description') && <p className="text-sm text-slate-500 mt-2">{text(c, 'description')}</p>}</div>{list.length ? <div className={section.sectionType === 'featured_course' ? 'max-w-xl' : section.sectionType === 'course_carousel' ? 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4' : 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5'}>{list.map((course) => <CourseCard key={course.id} course={course} onNavigate={onNavigate} />)}</div> : <div className="rounded-2xl bg-white border p-8 text-center text-sm text-slate-500">لا توجد دورات منشورة للعرض حاليًا.</div>}<CTA label={text(c, 'ctaLabel', 'عرض جميع الدورات')} target={text(c, 'ctaTarget', 'courses')} onNavigate={onNavigate} secondary /></div>); }
  if (section.sectionType === 'benefits' || section.sectionType === 'trust_badges') { const items = objects(c, 'items'); return wrap(<div className="space-y-6"><div className="text-center"><h2 className="text-2xl sm:text-3xl font-black">{text(c, 'titleAr', section.sectionType === 'benefits' ? 'لماذا English30؟' : 'تعلّم بثقة')}</h2><p className="text-sm text-slate-500 mt-2">{text(c, 'description')}</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{(items.length ? items : [{titleAr:'شرح عربي واضح',description:'دروس مصممة للمتعلم العربي.'},{titleAr:'مسار منظم',description:'تدرّج واضح بين المستويات.'},{titleAr:'تمارين تفاعلية',description:'تطبيق قصير بعد كل درس.'},{titleAr:'متابعة التقدم',description:'اعرف أين وصلت دائمًا.'}]).map((item,index) => <div key={index} className="bg-white border rounded-2xl p-5 space-y-3"><div className="w-11 h-11 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center"><CheckCircle2 className="w-5 h-5" /></div><h3 className="font-black">{text(item,'titleAr')}</h3><p className="text-sm text-slate-500 leading-6">{text(item,'description')}</p></div>)}</div></div>); }
  if (section.sectionType === 'statistics') return wrap(<div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{objects(c, 'items').map((item,index) => <div key={index} className="bg-white border rounded-2xl p-5 text-center"><div className="text-2xl font-black text-indigo-600">{text(item,'value')}</div><div className="text-xs text-slate-500 mt-1">{text(item,'labelAr')}</div></div>)}</div>);
  if (section.sectionType === 'countdown') return wrap(<div className="rounded-3xl bg-slate-950 text-white p-7 sm:p-10 flex flex-wrap items-center justify-between gap-5"><div><h2 className="text-2xl font-black">{text(c,'titleAr','ينتهي العرض قريبًا')}</h2><p className="text-sm text-slate-300 mt-2">{text(c,'description')}</p></div><Countdown target={text(c,'targetAt')} /></div>);
  if (section.sectionType === 'video') return wrap(<div className="rounded-3xl overflow-hidden bg-slate-950 text-white"><div className="aspect-video relative">{text(c,'videoUrl') ? <video controls preload="metadata" poster={text(c,'posterUrl') || undefined} className="w-full h-full object-cover"><source src={text(c,'videoUrl')} /></video> : text(c,'posterUrl') ? <img src={text(c,'posterUrl')} alt={text(c,'altText')} loading="lazy" className="w-full h-full object-cover" /> : <div className="h-full flex items-center justify-center"><Play className="w-14 h-14" /></div>}</div><div className="p-5"><h2 className="text-xl font-black">{text(c,'titleAr','تعلّم بطريقة عملية')}</h2><p className="text-sm text-slate-300 mt-2">{text(c,'description')}</p></div></div>);
  if (section.sectionType === 'text_content' || section.sectionType === 'custom_safe' || section.sectionType === 'blog_teaser' || section.sectionType === 'app_promo') return wrap(<div className="rounded-3xl bg-white border p-7 sm:p-10 space-y-3"><h2 className="text-2xl font-black">{text(c,'titleAr','')}</h2><p className="text-sm text-slate-600 leading-8 whitespace-pre-line">{text(c,'body', text(c,'description', ''))}</p>{text(c,'ctaLabel') && <CTA label={text(c,'ctaLabel')} target={text(c,'ctaTarget')} onNavigate={onNavigate} />}</div>);
  if (section.sectionType === 'faq') return wrap(<div className="space-y-5"><h2 className="text-2xl font-black">{text(c,'titleAr','الأسئلة الشائعة')}</h2><div className="space-y-2">{objects(c,'items').map((item,index) => <details key={index} className="bg-white border rounded-2xl p-4"><summary className="font-black cursor-pointer">{text(item,'question')}</summary><p className="text-sm text-slate-600 leading-7 mt-3">{text(item,'answer')}</p></details>)}</div></div>);
  if (section.sectionType === 'pricing_highlight' || section.sectionType === 'placement_test' || section.sectionType === 'certificate_promotion' || section.sectionType === 'cta') return wrap(<div className="rounded-3xl bg-gradient-to-r from-indigo-700 to-violet-700 text-white p-7 sm:p-10 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-5"><div><h2 className="text-2xl font-black">{text(c,'titleAr', section.sectionType === 'placement_test' ? 'لا تعرف مستواك؟' : 'ابدأ خطوتك التالية')}</h2><p className="text-sm text-white/80 mt-2 leading-7">{text(c,'description','اختبر مستواك أو ابدأ التعلم الآن.')}</p></div><CTA label={text(c,'ctaLabel','ابدأ الآن')} target={text(c,'ctaTarget', section.sectionType === 'placement_test' ? 'placement-test' : 'pricing')} onNavigate={onNavigate} secondary /></div>);
  return null;
};

export const defaultHomepageSections = (settings: PlatformSettings): HomepageSection[] => [
  { id: 'default-hero', sectionType: 'hero', sortOrder: 0, enabled: true, status: 'published', config: { variant: settings.heroImageUrl ? 'background' : 'gradient', titleAr: settings.heroHeadlineAr, subtitle: settings.heroSubheadlineAr, badge: settings.homepageBadgeAr, imageUrl: settings.heroImageUrl, primaryLabel: settings.heroPrimaryCtaLabelAr, primaryTarget: settings.heroPrimaryCtaTarget, secondaryLabel: settings.heroSecondaryCtaLabelAr, secondaryTarget: settings.heroSecondaryCtaTarget } },
  { id: 'default-benefits', sectionType: 'benefits', sortOrder: 1, enabled: true, status: 'published', config: { titleAr: 'لماذا English30؟' } },
  { id: 'default-courses', sectionType: 'course_grid', sortOrder: 2, enabled: true, status: 'published', config: { titleAr: 'الدورات المنشورة', limit: 6 } },
  { id: 'default-placement', sectionType: 'placement_test', sortOrder: 3, enabled: true, status: 'published', config: { titleAr: 'ابدأ من المستوى المناسب لك', description: 'اختبار قصير يساعدك على معرفة نقطة البداية.', ctaLabel: 'اختبار تحديد المستوى', ctaTarget: 'placement-test' } },
];
