export { settingsService, DEFAULT_PLATFORM_SETTINGS } from './settingsService';
export { coursesService } from './coursesService';
export { lessonsService } from './lessonsService';
export { questionsService } from './questionsService';
export { studentsService } from './studentsService';
export { subscriptionsService } from './subscriptionsService';
export { paymentService } from './paymentService';
export { videoService } from './videoService';
export { progressService } from './progressService';
export { quizService } from './quizService';
export { auditService } from './auditService';
export { ownerAIService } from './ownerAIService';
export { supabase, isSupabaseConfigured, getSupabaseClient } from '../lib/supabase';
