export { settingsService, DEFAULT_PLATFORM_SETTINGS } from './settingsService';
export { coursesService } from './coursesService';
export { lessonsService } from './lessonsService';
export { questionsService } from './questionsService';
export { studentsService } from './studentsService';
export { subscriptionsService } from './subscriptionsServiceSupabase';
export { paymentService } from './paymentServiceProduction';
export { auditService } from './auditService';
export { ownerAIService } from './ownerAIService';
export { authService } from './authService';
export { supabase, isSupabaseConfigured, getSupabaseClient } from '../lib/supabase';
