export { settingsService, DEFAULT_PLATFORM_SETTINGS } from './settingsService';
export { coursesService } from './coursesService';
export { lessonsService } from './lessonsService';
export { progressService } from './progressService';
export { questionsService } from './questionsService';
export { studentsService } from './studentsService';
export { subscriptionsService } from './subscriptionsServiceSupabase';
export { paymentService, PaymentService } from './paymentService';
export { ProductionPaymentGateway } from './paymentServiceProduction';
export type { IPaymentGateway, PaymentGatewayInfo } from './payments/IPaymentGateway';
export { videoService, VideoService } from './videoService';
export type { IVideoProvider, VideoPlayback, VideoSource } from './videoService';
export { quizService, QuizService } from './quizService';
export { auditService } from './auditService';
export { ownerAIService } from './ownerAIService';
export { aiContentDraftsService } from './aiContentDraftsService';
export { authService } from './authService';
export { mediaService } from './mediaService';
export type { MediaAsset } from './mediaService';
export { supabase, isSupabaseConfigured, getSupabaseClient } from '../lib/supabase';
