import { getSupabaseClient, isSupabaseConfigured } from '../lib/supabase';

export interface MediaAsset { id:string; bucketId:string; storagePath:string; fileName:string; mimeType?:string; sizeBytes?:number; altText?:string; kind:'image'|'video'|'audio'|'document'|'other'; createdAt:string; }

const kindOf=(mime:string):MediaAsset['kind']=>mime.startsWith('image/')?'image':mime.startsWith('video/')?'video':mime.startsWith('audio/')?'audio':mime==='application/pdf'?'document':'other';

class MediaService {
  async list(bucketId='lesson-media'):Promise<MediaAsset[]> { if(!isSupabaseConfigured)return []; const {data,error}=await getSupabaseClient().from('media_assets').select('*').eq('bucket_id',bucketId).order('created_at',{ascending:false}); if(error)throw error; return (data??[]).map((r:any)=>({id:r.id,bucketId:r.bucket_id,storagePath:r.storage_path,fileName:r.file_name,mimeType:r.mime_type??undefined,sizeBytes:r.size_bytes??undefined,altText:r.alt_text??undefined,kind:r.kind,createdAt:r.created_at})); }
  async upload(file:File,bucketId='lesson-media',folder='library',altText=''):Promise<MediaAsset>{ if(!isSupabaseConfigured)throw new Error('Supabase is not configured.'); const user=(await getSupabaseClient().auth.getUser()).data.user; if(!user)throw new Error('يجب تسجيل الدخول.'); const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-'); const path=`${folder}/${crypto.randomUUID()}-${safe}`; const {error}=await getSupabaseClient().storage.from(bucketId).upload(path,file,{contentType:file.type,upsert:false}); if(error)throw error; const {data,error:insertError}=await getSupabaseClient().from('media_assets').insert({uploaded_by:user.id,bucket_id:bucketId,storage_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size,alt_text:altText||null,kind:kindOf(file.type)}).select('*').single(); if(insertError){await getSupabaseClient().storage.from(bucketId).remove([path]);throw insertError;} return {id:data.id,bucketId:data.bucket_id,storagePath:data.storage_path,fileName:data.file_name,mimeType:data.mime_type??undefined,sizeBytes:data.size_bytes??undefined,altText:data.alt_text??undefined,kind:data.kind,createdAt:data.created_at}; }
  async createSignedUrl(asset:MediaAsset,expiresIn=3600){if(!isSupabaseConfigured)throw new Error('Supabase is not configured.');const {data,error}=await getSupabaseClient().storage.from(asset.bucketId).createSignedUrl(asset.storagePath,expiresIn);if(error)throw error;return data.signedUrl;}
  async remove(asset:MediaAsset){if(!isSupabaseConfigured)throw new Error('Supabase is not configured.');const {error}=await getSupabaseClient().storage.from(asset.bucketId).remove([asset.storagePath]);if(error)throw error;const {error:dbError}=await getSupabaseClient().from('media_assets').delete().eq('id',asset.id);if(dbError)throw dbError;}
}
export const mediaService=new MediaService();
