import { PricingPlan, CouponItem, CouponValidationResult } from '../types';
import { getSupabaseClient, isSupabaseConfigured } from '../lib/supabase';

type Listener=(data:{plans:PricingPlan[];coupons:CouponItem[]})=>void;
class SupabaseSubscriptionsService {
 private plans:PricingPlan[]=[]; private coupons:CouponItem[]=[]; private listeners=new Set<Listener>();
 async getPlans(){if(!isSupabaseConfigured)return [];const {data,error}=await getSupabaseClient().from('plans').select('*,plan_prices(*)').eq('is_active',true).order('sort_order');if(error)throw error;this.plans=(data??[] as any[]).map((p:any)=>{const prices=p.plan_prices??[];const m=prices.find((x:any)=>x.interval==='month'&&x.is_active);const y=prices.find((x:any)=>x.interval==='year'&&x.is_active);return {id:p.id,nameAr:p.name,nameEn:p.name,descriptionAr:p.description??'',featuresAr:Array.isArray(p.features)?p.features:[],priceMonthly:Number(m?.amount??0),priceYearly:Number(y?.amount??0),buttonTextAr:'اشترك الآن',isActive:p.is_active,currency:m?.currency??'SAR'};});this.notify();return [...this.plans];}
 async getPlanById(id:string){return (await this.getPlans()).find(p=>p.id===id);}
 async updatePlan(id:string,u:Partial<PricingPlan>){if(!isSupabaseConfigured)throw new Error('Supabase is required.');const payload:any={};if(u.nameAr!==undefined)payload.name=u.nameAr;if(u.descriptionAr!==undefined)payload.description=u.descriptionAr;if(u.isActive!==undefined)payload.is_active=u.isActive;const {error}=await getSupabaseClient().from('plans').update(payload).eq('id',id);if(error)throw error;await this.getPlans();return this.plans.find(p=>p.id===id)??null;}
 async getCoupons(){if(!isSupabaseConfigured)return [];const {data,error}=await getSupabaseClient().from('coupons').select('*').order('created_at',{ascending:false});if(error)throw error;this.coupons=(data??[] as any[]).map((c:any)=>({id:c.id,code:c.code,discountPercentage:c.discount_type==='percentage'?Number(c.discount_value):0,maxRedemptions:c.max_redemptions,timesRedeemed:c.redeemed_count,expiresAt:c.expires_at??undefined,isActive:c.is_active}));this.notify();return [...this.coupons];}
 async validateCoupon(raw:string):Promise<CouponValidationResult>{const code=raw.trim().toUpperCase();if(!code)return {valid:false,discountPercentage:0,messageAr:'الرجاء إدخال كود الخصم.'};const {data,error}=await getSupabaseClient().from('coupons').select('*').eq('code',code).eq('is_active',true).maybeSingle();if(error)throw error;if(!data)return {valid:false,discountPercentage:0,messageAr:'كود الخصم غير صحيح أو غير موجود.'};if(data.starts_at&&new Date(data.starts_at)>new Date())return {valid:false,discountPercentage:0,messageAr:'لم يبدأ هذا الكوبون بعد.'};if(data.expires_at&&new Date(data.expires_at)<new Date())return {valid:false,discountPercentage:0,messageAr:'انتهت صلاحية هذا الكوبون.'};if(data.redeemed_count>=data.max_redemptions)return {valid:false,discountPercentage:0,messageAr:'وصل الكوبون للحد الأقصى.'};if(data.discount_type!=='percentage')return {valid:false,discountPercentage:0,messageAr:'نوع الخصم غير مدعوم حالياً.'};const c={id:data.id,code:data.code,discountPercentage:Number(data.discount_value),maxRedemptions:data.max_redemptions,timesRedeemed:data.redeemed_count,expiresAt:data.expires_at??undefined,isActive:data.is_active};return {valid:true,discountPercentage:c.discountPercentage,messageAr:`تم تطبيق خصم ${c.discountPercentage}% بنجاح! 🎉`,coupon:c};}
 async createCoupon(d:Omit<CouponItem,'id'|'timesRedeemed'>){const {data,error}=await getSupabaseClient().from('coupons').insert({code:d.code.trim().toUpperCase(),discount_type:'percentage',discount_value:d.discountPercentage,max_redemptions:d.maxRedemptions,expires_at:d.expiresAt??null,is_active:d.isActive}).select('*').single();if(error)throw error;await this.getCoupons();return {id:data.id,code:data.code,discountPercentage:Number(data.discount_value),maxRedemptions:data.max_redemptions,timesRedeemed:data.redeemed_count,expiresAt:data.expires_at??undefined,isActive:data.is_active};}
 async deleteCoupon(id:string){const {error}=await getSupabaseClient().from('coupons').delete().eq('id',id);if(error)throw error;await this.getCoupons();return true;}
 async toggleCouponStatus(id:string){const c=(await this.getCoupons()).find(x=>x.id===id);if(!c)return null;const {error}=await getSupabaseClient().from('coupons').update({is_active:!c.isActive}).eq('id',id);if(error)throw error;await this.getCoupons();return this.coupons.find(x=>x.id===id)??null;}
 async getFinancialMetrics(){const [{data:s,error:se},{data:p,error:pe}]=await Promise.all([getSupabaseClient().from('subscriptions').select('status'),getSupabaseClient().from('payments').select('amount,status')]);if(se)throw se;if(pe)throw pe;const paid=(p??[]).filter((x:any)=>x.status==='paid');const active=(s??[]).filter((x:any)=>x.status==='active').length;const revenue=paid.reduce((n:number,x:any)=>n+Number(x.amount||0),0);return {monthlyRecurringRevenueSAR:0,annualRevenueRunRateSAR:0,averageRevenuePerUserSAR:active?Math.round(revenue/active):0,activePaidSubscribers:active,totalSuccessfulTransactions:paid.length};}
 subscribe(l:Listener){this.listeners.add(l);void Promise.all([this.getPlans(),this.getCoupons()]).then(()=>l({plans:[...this.plans],coupons:[...this.coupons]})).catch(console.error);return()=>this.listeners.delete(l);}
 private notify(){this.listeners.forEach(l=>l({plans:[...this.plans],coupons:[...this.coupons]}));}
}
export const subscriptionsService=new SupabaseSubscriptionsService();