import React, { useMemo, useState } from 'react';
import { Eye, Loader2, Save, X } from 'lucide-react';
import type { HomepageSection, HomepageSectionType, VisualAnimationPreset } from '../../types';
import { homepageService, SECTION_LABELS } from '../../services';
import { MediaImagePicker } from './MediaImagePicker';

interface Props { section: HomepageSection; onClose: () => void; onSaved: () => void; }
const animationOptions: Array<[VisualAnimationPreset, string]> = [['none','بدون حركة'],['fade_in','تلاشي'],['fade_up','ظهور من الأسفل'],['slide_left','انزلاق من اليسار'],['slide_right','انزلاق من اليمين'],['zoom_subtle','تكبير لطيف'],['staggered_cards','بطاقات متتابعة'],['soft_parallax','عمق لطيف'],['marquee','شريط متحرك'],['count_up','عدّ تصاعدي'],['gentle_float','طفو لطيف']];
const heroVariants: Array<[string,string]> = [['gradient','تدرج لوني'],['background','صورة خلفية'],['split','نص وصورة متقابلان'],['video','فيديو خلفي'],['carousel','شرائح متعددة'],['text','نصي بسيط']];
const textValue = (config: Record<string, unknown>, key: string) => typeof config[key] === 'string' ? config[key] as string : '';

export const HomepageSectionEditor: React.FC<Props> = ({ section, onClose, onSaved }) => {
  const [config, setConfig] = useState<Record<string, unknown>>({ ...section.config });
  const [sectionType, setSectionType] = useState<HomepageSectionType>(section.sectionType);
  const [sortOrder, setSortOrder] = useState(section.sortOrder);
  const [enabled, setEnabled] = useState(section.enabled);
  const [preview, setPreview] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const set = (key: string, value: unknown) => setConfig((current) => ({ ...current, [key]: value }));
  const title = useMemo(() => textValue(config, 'titleAr') || 'معاينة القسم', [config]);
  const save = async () => { setBusy(true); setError(''); try { await homepageService.saveSection({ id: section.id.startsWith('default-') || section.id === 'new-section' ? undefined : section.id, sectionType, sortOrder: Math.max(0, Math.min(9999, sortOrder)), enabled, config }); onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر حفظ القسم.'); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-[120] bg-slate-950/70 backdrop-blur-sm p-4 flex items-center justify-center" dir="rtl" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><section className="w-full max-w-3xl max-h-[92vh] overflow-y-auto bg-white rounded-3xl shadow-2xl p-6 space-y-5"><header className="flex items-center justify-between gap-3"><div><p className="text-[11px] font-black text-amber-600">تحرير بصري آمن</p><h2 className="text-xl font-black">{SECTION_LABELS[sectionType]}</h2><p className="text-xs text-slate-500 mt-1">تعديلات منظمة دون CSS أو HTML أو JavaScript مخصص.</p></div><button type="button" onClick={onClose} disabled={busy} className="p-2 rounded-xl bg-slate-100"><X className="w-5 h-5" /></button></header>{error && <div className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm">{error}</div>}
    <div className="grid sm:grid-cols-3 gap-3"><label className="text-xs font-black">نوع القسم<select value={sectionType} onChange={(event) => setSectionType(event.target.value as HomepageSectionType)} className="mt-2 w-full border rounded-xl p-2.5 text-sm font-normal">{Object.entries(SECTION_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-black">الترتيب<input type="number" min={0} max={9999} value={sortOrder} onChange={(event) => setSortOrder(Number(event.target.value))} className="mt-2 w-full border rounded-xl p-2.5 text-sm font-normal" /></label><label className="text-xs font-black flex items-center gap-2 pt-6"><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} /> إظهار القسم للزوار</label></div>
    <div className="grid sm:grid-cols-2 gap-4"><label className="text-xs font-black">العنوان<label className="sr-only">العنوان</label><input value={textValue(config,'titleAr')} onChange={(event) => set('titleAr',event.target.value)} className="mt-2 w-full border rounded-xl p-3 text-sm font-normal" /></label><label className="text-xs font-black">الوصف<input value={textValue(config,'description')} onChange={(event) => set('description',event.target.value)} className="mt-2 w-full border rounded-xl p-3 text-sm font-normal" /></label><label className="text-xs font-black sm:col-span-2">النص التفصيلي<textarea rows={3} value={textValue(config,'body')} onChange={(event) => set('body',event.target.value)} className="mt-2 w-full border rounded-xl p-3 text-sm font-normal" /></label></div>
    {sectionType === 'hero' && <div className="rounded-2xl bg-slate-50 border p-4 space-y-4"><h3 className="font-black text-sm">إعدادات البطل</h3><div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-black">نمط البطل<select value={textValue(config,'variant') || 'gradient'} onChange={(event) => set('variant',event.target.value)} className="mt-2 w-full border rounded-xl p-2.5 text-sm font-normal">{heroVariants.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-black">محاذاة المحتوى<select value={textValue(config,'align') || 'center'} onChange={(event) => set('align',event.target.value)} className="mt-2 w-full border rounded-xl p-2.5 text-sm font-normal"><option value="center">وسط</option><option value="right">يمين</option><option value="left">يسار</option></select></label><label className="text-xs font-black">نص الزر الرئيسي<input value={textValue(config,'primaryLabel')} onChange={(event) => set('primaryLabel',event.target.value)} className="mt-2 w-full border rounded-xl p-2.5 text-sm font-normal" /></label><label className="text-xs font-black">وجهة الزر الرئيسي<input dir="ltr" value={textValue(config,'primaryTarget')} onChange={(event) => set('primaryTarget',event.target.value)} placeholder="courses أو https://..." className="mt-2 w-full border rounded-xl p-2.5 text-sm font-normal" /></label><label className="text-xs font-black">نص الزر الثانوي<input value={textValue(config,'secondaryLabel')} onChange={(event) => set('secondaryLabel',event.target.value)} className="mt-2 w-full border rounded-xl p-2.5 text-sm font-normal" /></label><label className="text-xs font-black">وجهة الزر الثانوي<input dir="ltr" value={textValue(config,'secondaryTarget')} onChange={(event) => set('secondaryTarget',event.target.value)} className="mt-2 w-full border rounded-xl p-2.5 text-sm font-normal" /></label></div><MediaImagePicker label="صورة سطح المكتب / الخلفية" valueUrl={textValue(config,'imageUrl')} onChange={(value) => set('imageUrl',value?.url || '')} folder="branding" /><MediaImagePicker label="صورة الجوال الاختيارية" valueUrl={textValue(config,'mobileImageUrl')} onChange={(value) => set('mobileImageUrl',value?.url || '')} folder="branding" /></div>}
    {(sectionType === 'promotional_banner' || sectionType === 'image_text_split' || sectionType === 'image_carousel' || sectionType === 'video') && <MediaImagePicker label="الصورة أو الملصق الاحتياطي" valueUrl={textValue(config,'imageUrl') || textValue(config,'posterUrl')} onChange={(value) => set(sectionType === 'video' ? 'posterUrl' : 'imageUrl',value?.url || '')} folder="branding" />}
    {sectionType === 'video' && <label className="block text-xs font-black">رابط الفيديو الخارجي / Bunny لاحقًا<input dir="ltr" value={textValue(config,'videoUrl')} onChange={(event) => set('videoUrl',event.target.value)} placeholder="https://..." className="mt-2 w-full border rounded-xl p-3 text-sm font-normal" /><span className="block mt-1 text-[10px] text-slate-500 font-normal">يُعرض الفيديو مكتومًا فقط عند استخدامه كخلفية، مع صورة احتياطية للجوال.</span></label>}
    <div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-black">الحركة<select value={textValue(config,'animation') || 'none'} onChange={(event) => set('animation',event.target.value)} className="mt-2 w-full border rounded-xl p-2.5 text-sm font-normal">{animationOptions.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs font-black flex items-center gap-2 pt-6"><input type="checkbox" checked={Boolean(config.showCountdown)} onChange={(event) => set('showCountdown',event.target.checked)} /> إظهار العد التنازلي</label></div>
    {preview && <div className="rounded-2xl border-2 border-indigo-200 bg-indigo-50 p-5"><p className="text-xs font-black text-indigo-700 mb-2">معاينة مختصرة قبل الحفظ</p><h3 className="text-xl font-black">{title}</h3><p className="text-sm text-slate-600 mt-2">{textValue(config,'description') || 'سيظهر المحتوى هنا وفق النمط المختار.'}</p>{textValue(config,'imageUrl') && <img src={textValue(config,'imageUrl')} alt="" className="mt-4 max-h-40 w-full object-cover rounded-xl" />}</div>}
    <footer className="flex flex-wrap justify-end gap-2"><button type="button" onClick={onClose} disabled={busy} className="px-4 py-2.5 rounded-xl border text-sm font-bold">إلغاء</button><button type="button" onClick={() => setPreview((value) => !value)} disabled={busy} className="px-4 py-2.5 rounded-xl bg-indigo-50 text-indigo-700 text-sm font-black flex items-center gap-2"><Eye className="w-4 h-4" />معاينة</button><button type="button" onClick={() => void save()} disabled={busy} className="px-5 py-2.5 rounded-xl bg-indigo-600 text-white text-sm font-black flex items-center gap-2">{busy ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}حفظ كمسودة</button></footer>
  </section></div>;
};
