import React, { FormEvent, useEffect, useMemo, useState } from 'react';
import { KeyRound, Plus, RefreshCw, Search, ShieldOff, UserCog } from 'lucide-react';
import type { PermissionCode, PermissionDefinition, StaffPermissionAssignment } from '../../types';
import { permissionsService } from '../../services/permissionsService';

const formatDate = (value?: string) => value ? new Date(value).toLocaleString('ar-SA') : 'لا يوجد نشاط مسجل';

export const OwnerPermissions: React.FC = () => {
  const [definitions, setDefinitions] = useState<PermissionDefinition[]>([]);
  const [members, setMembers] = useState<StaffPermissionAssignment[]>([]);
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<StaffPermissionAssignment | null>(null);
  const [grants, setGrants] = useState<Set<PermissionCode>>(new Set());
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const load = async (query = '') => { const data = await permissionsService.load(query); setDefinitions(data.definitions); setMembers(data.staff); };
  useEffect(() => { void load().catch((reason) => setError(reason.message)); }, []);
  const admins = useMemo(() => members.filter((member) => member.roles.includes('admin')), [members]);
  const candidates = useMemo(() => members.filter((member) => !member.roles.includes('admin')), [members]);
  const open = (member: StaffPermissionAssignment) => { setSelected(member); setGrants(new Set(definitions.filter((definition) => member.permissions[definition.code] === true).map((definition) => definition.code))); setError(''); setSuccess(''); };
  const submitSearch = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await load(search); } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر البحث.'); } finally { setBusy(false); } };
  const save = async () => { if (!selected) return; setBusy(true); setError(''); try { await permissionsService.saveAdmin(selected.userId, true, [...grants]); setSuccess('تم حفظ دور المدير وصلاحياته في قاعدة البيانات.'); await load(search); setSelected(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر حفظ المدير.'); } finally { setBusy(false); } };
  const revoke = async (member: StaffPermissionAssignment) => { if (!window.confirm(`إزالة صلاحية المدير من ${member.email}؟`)) return; setBusy(true); setError(''); try { await permissionsService.saveAdmin(member.userId, false, []); setSuccess('تم إلغاء وصول المدير وتوثيق العملية.'); await load(search); } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر إلغاء وصول المدير.'); } finally { setBusy(false); } };

  return <section className="space-y-6" dir="rtl"><div><h2 className="text-2xl font-black">الأدوار والصلاحيات</h2><p className="text-sm text-slate-500 mt-1">إدارة المديرين من خلال عملية Owner-only ذرّية. لا يمكن للمدير تعديل دوره أو صلاحياته أو إنشاء مالك.</p></div>
    {error && <div className="p-4 bg-red-50 border border-red-200 text-red-700 rounded-2xl text-sm">{error}</div>}{success && <div className="p-4 bg-emerald-50 border border-emerald-200 text-emerald-700 rounded-2xl text-sm">{success}</div>}
    <div className="bg-white border rounded-3xl p-5 space-y-4"><h3 className="font-black flex gap-2"><Plus className="w-5 h-5 text-indigo-600"/>إضافة مدير</h3><form onSubmit={submitSearch} className="flex flex-col sm:flex-row gap-2"><input value={search} onChange={(event) => setSearch(event.target.value)} minLength={2} required placeholder="ابحث بالبريد أو الاسم لمستخدم مسجل" className="flex-1 border rounded-xl p-3 text-sm"/><button disabled={busy} className="px-5 py-3 bg-indigo-600 text-white rounded-xl font-black text-sm flex gap-2 justify-center"><Search className="w-4 h-4"/>بحث آمن</button></form>{search.trim().length >= 2 && candidates.length === 0 && <p className="text-sm text-slate-500">لا يوجد مستخدم مطابق غير مضاف كمدير.</p>}{candidates.map((member) => <button key={member.userId} onClick={() => open(member)} className="w-full border rounded-2xl p-4 text-right hover:border-indigo-300"><strong className="block text-sm">{member.fullName}</strong><span className="text-xs text-slate-500">{member.email} · {member.isSuspended ? 'موقوف' : member.isActive ? 'نشط' : 'غير نشط'}</span></button>)}</div>
    <div className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-black flex gap-2"><UserCog className="w-5 h-5 text-indigo-600"/>المديرون الحاليون</h3><button onClick={() => void load(search)} className="p-2 border rounded-xl"><RefreshCw className="w-4 h-4"/></button></div>{admins.length === 0 && <div className="bg-white border rounded-3xl p-8 text-center text-slate-500 text-sm">لا يوجد مديرون حاليًا.</div>}{admins.map((member) => <article key={member.userId} className="bg-white border rounded-3xl p-5 flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><h4 className="font-black flex gap-2"><KeyRound className="w-4 h-4 text-indigo-600"/>{member.fullName}</h4><p className="text-xs text-slate-500 mt-1">{member.email}</p><p className="text-[11px] mt-2 text-slate-500">آخر نشاط: {formatDate(member.lastActiveAt)} · {member.isSuspended ? 'موقوف' : member.isActive ? 'نشط' : 'غير نشط'}</p><div className="flex flex-wrap gap-1 mt-3">{definitions.filter((definition) => member.permissions[definition.code] === true).map((definition) => <span key={definition.code} className="text-[10px] bg-emerald-50 text-emerald-700 px-2 py-1 rounded-full">{definition.nameAr}</span>)}</div></div><div className="flex gap-2"><button onClick={() => open(member)} className="px-4 py-2 bg-indigo-50 text-indigo-700 rounded-xl text-xs font-black">تعديل الصلاحيات</button><button disabled={busy} onClick={() => void revoke(member)} className="px-4 py-2 bg-red-50 text-red-700 rounded-xl text-xs font-black flex gap-2"><ShieldOff className="w-4 h-4"/>إلغاء وصول المدير</button></div></article>)}</div>
    {selected && <div className="fixed inset-0 z-[90] bg-slate-950/70 p-4 flex items-center justify-center"><div className="bg-white rounded-3xl p-6 w-full max-w-3xl max-h-[90vh] overflow-auto space-y-5"><div><h3 className="text-xl font-black">{selected.roles.includes('admin') ? 'تعديل صلاحيات المدير' : 'إضافة مدير'}</h3><p className="text-sm text-slate-500">{selected.fullName} · {selected.email}</p></div>{selected.isSuspended && <div className="bg-amber-50 border border-amber-200 p-3 rounded-xl text-amber-800 text-xs">الحساب موقوف؛ تعيين الدور لا يتجاوز الإيقاف.</div>}<div className="grid sm:grid-cols-2 gap-2">{definitions.map((definition) => <label key={definition.code} className={`border rounded-xl p-3 flex gap-3 cursor-pointer ${grants.has(definition.code) ? 'bg-emerald-50 border-emerald-200' : 'bg-slate-50'}`}><input type="checkbox" checked={grants.has(definition.code)} onChange={() => setGrants((current) => { const next = new Set(current); next.has(definition.code) ? next.delete(definition.code) : next.add(definition.code); return next; })}/><span><strong className="block text-xs">{definition.nameAr}</strong><small className="text-[10px] text-slate-500">{definition.descriptionAr}</small></span></label>)}</div><p className="text-[11px] text-slate-500">الاستيراد والتصدير يتطلب صلاحيات المحتوى والاختبارات والشهادات معًا. صلاحية إدارة الأدوار محجوزة للمالك ولا تظهر هنا.</p><div className="flex justify-end gap-2"><button disabled={busy} onClick={() => setSelected(null)} className="px-4 py-2 border rounded-xl text-sm font-bold">إلغاء</button><button disabled={busy || selected.isSuspended || selected.isActive === false} onClick={() => void save()} className="px-5 py-2 bg-indigo-600 text-white rounded-xl text-sm font-black">{busy ? 'جاري الحفظ...' : 'حفظ المدير والصلاحيات'}</button></div></div></div>}
  </section>;
};
