import React, { useEffect, useState } from 'react';
import { Download, FileJson, Upload } from 'lucide-react';
import { Course } from '../../types';
import { coursesService, ownerCmsService } from '../../services';

export const OwnerImportExport:React.FC=()=>{
  const [courses,setCourses]=useState<Course[]>([]);const [courseId,setCourseId]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
  const load=async()=>{const rows=await coursesService.getCourses();setCourses(rows);setCourseId(current=>current||rows[0]?.id||'');};useEffect(()=>{void load().catch(reason=>setError(reason.message));},[]);
  const exportCourse=async()=>{if(!courseId)return;setBusy(true);setError('');try{const payload=await ownerCmsService.exportCourse(courseId);const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`english30-course-${courseId}.json`;anchor.click();URL.revokeObjectURL(url);setMessage('تم إنشاء ملف التصدير دون بيانات طلاب أو مدفوعات أو أسرار.');}catch(reason){setError(reason instanceof Error?reason.message:'تعذر التصدير.');}finally{setBusy(false);}};
  const importFile=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setBusy(true);setError('');setMessage('');try{if(file.size>5_000_000)throw new Error('حجم ملف الاستيراد يتجاوز 5MB.');const payload=JSON.parse(await file.text());const id=await ownerCmsService.importCourse(payload);setMessage(`تم الاستيراد كمسودة جديدة: ${id}`);await load();}catch(reason){setError(reason instanceof Error?reason.message:'ملف غير صالح.');}finally{setBusy(false);event.target.value='';}};
  return <section className="space-y-6" dir="rtl"><div><h2 className="text-2xl font-black">استيراد وتصدير الدورات</h2><p className="text-sm text-slate-500 mt-1">تنسيق JSON محمول يشمل المحتوى المنظم والاختبارات فقط، ولا يشمل الطلاب أو المدفوعات أو الأسرار.</p></div>{message&&<div className="p-4 bg-emerald-50 border border-emerald-200 text-emerald-700 rounded-2xl text-sm">{message}</div>}{error&&<div className="p-4 bg-red-50 border border-red-200 text-red-700 rounded-2xl text-sm">{error}</div>}<div className="grid md:grid-cols-2 gap-5"><article className="bg-white border rounded-3xl p-6 space-y-4"><Download className="w-8 h-8 text-indigo-600"/><h3 className="font-black">تصدير دورة</h3><select value={courseId} onChange={e=>setCourseId(e.target.value)} className="w-full border rounded-xl p-3 text-sm">{courses.map(course=><option key={course.id} value={course.id}>{course.titleAr}</option>)}</select><button disabled={busy||!courseId} onClick={()=>void exportCourse()} className="px-5 py-3 bg-indigo-600 text-white rounded-xl text-sm font-black">تنزيل JSON</button></article><article className="bg-white border rounded-3xl p-6 space-y-4"><Upload className="w-8 h-8 text-emerald-600"/><h3 className="font-black">استيراد آمن</h3><p className="text-xs text-slate-500">تتحقق قاعدة البيانات من الإصدار والبنية، وتُنشأ الدورة ودروسها دائمًا كمسودات.</p><label className="inline-flex px-5 py-3 bg-emerald-600 text-white rounded-xl text-sm font-black cursor-pointer"><FileJson className="w-4 h-4 ml-2"/>{busy?'جاري الفحص...':'اختيار ملف JSON'}<input type="file" accept="application/json,.json" onChange={importFile} disabled={busy} className="hidden"/></label></article></div></section>;
};
