import React, { useEffect, useState } from 'react';
import { mediaService, MediaAsset, PRIVATE_LESSON_MEDIA_BUCKET, PUBLIC_SITE_ASSETS_BUCKET } from '../../services';
import { Archive, FileText, Image as ImageIcon, Music, RefreshCw, RotateCcw, Save, Upload, Video } from 'lucide-react';

const formatSize = (bytes?: number) => bytes ? bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.round(bytes / 1024)} KB` : '—';
const dimensions = (asset: MediaAsset) => Number(asset.metadata.width) > 0 && Number(asset.metadata.height) > 0 ? `${asset.metadata.width}×${asset.metadata.height}` : 'الأبعاد غير متاحة';

export const OwnerMediaLibrary: React.FC = () => {
  const [assets,setAssets] = useState<MediaAsset[]>([]); const [bucket,setBucket] = useState(PUBLIC_SITE_ASSETS_BUCKET); const [loading,setLoading] = useState(true); const [busy,setBusy] = useState(false); const [includeArchived,setIncludeArchived] = useState(false); const [error,setError] = useState(''); const [altDrafts,setAltDrafts] = useState<Record<string,string>>({});
  const load = async () => { setLoading(true); setError(''); try { const rows = await mediaService.listWithUrls(bucket,includeArchived); setAssets(rows); setAltDrafts(Object.fromEntries(rows.map((asset) => [asset.id,asset.altText||'']))); } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر تحميل المكتبة.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [bucket,includeArchived]);
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); setError(''); try { if (bucket === PUBLIC_SITE_ASSETS_BUCKET) await mediaService.uploadSiteImage(file,{folder:'library',allowFavicon:true}); else await mediaService.upload(file,PRIVATE_LESSON_MEDIA_BUCKET); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر رفع الملف.'); } finally { setBusy(false); event.target.value=''; } };
  const archive = async (asset: MediaAsset) => { if (!confirm(`أرشفة ${asset.fileName}؟ يمكن استعادته لاحقًا.`)) return; await mediaService.archive(asset); await load(); };
  const restore = async (asset: MediaAsset) => { await mediaService.restore(asset); await load(); };
  const saveAlt = async (asset: MediaAsset) => { setBusy(true); try { await mediaService.updateAltText(asset.id,altDrafts[asset.id]||''); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر حفظ النص البديل.'); } finally { setBusy(false); } };
  const icon = (kind: MediaAsset['kind']) => kind === 'image' ? <ImageIcon/> : kind === 'video' ? <Video/> : kind === 'audio' ? <Music/> : <FileText/>;

  return <section className="space-y-5" dir="rtl">
    <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div><h2 className="text-2xl font-black">مكتبة الوسائط</h2><p className="text-sm text-slate-500 mt-1">الصور العامة منفصلة عن ملفات الدروس الخاصة؛ لا تتحول وسائط الدروس المدفوعة إلى ملفات عامة.</p></div><div className="flex flex-wrap gap-2"><label className="px-3 py-2 rounded-xl border bg-white text-xs font-bold flex items-center gap-2"><input type="checkbox" checked={includeArchived} onChange={(e) => setIncludeArchived(e.target.checked)}/>عرض المؤرشف</label><button type="button" onClick={() => void load()} className="px-3 py-2 rounded-xl border bg-white text-xs font-bold"><RefreshCw className="inline w-4 h-4 ml-1"/>تحديث</button><label className="px-4 py-2 rounded-xl bg-indigo-600 text-white text-xs font-black cursor-pointer"><Upload className="inline w-4 h-4 ml-1"/>{busy?'جاري الرفع...':'رفع ملف'}<input type="file" className="hidden" accept={bucket===PUBLIC_SITE_ASSETS_BUCKET?'.png,.jpg,.jpeg,.webp,.ico,image/png,image/jpeg,image/webp,image/x-icon,image/vnd.microsoft.icon':'image/png,image/jpeg,image/webp,video/mp4,video/webm,audio/mpeg,audio/mp4,audio/wav,application/pdf'} onChange={upload} disabled={busy}/></label></div></div>
    <div className="inline-flex rounded-xl border bg-white p-1"><button type="button" onClick={() => setBucket(PUBLIC_SITE_ASSETS_BUCKET)} className={`px-4 py-2 rounded-lg text-xs font-black ${bucket===PUBLIC_SITE_ASSETS_BUCKET?'bg-indigo-600 text-white':'text-slate-600'}`}>صور الموقع العامة</button><button type="button" onClick={() => setBucket(PRIVATE_LESSON_MEDIA_BUCKET)} className={`px-4 py-2 rounded-lg text-xs font-black ${bucket===PRIVATE_LESSON_MEDIA_BUCKET?'bg-indigo-600 text-white':'text-slate-600'}`}>وسائط الدروس الخاصة</button></div>
    {bucket===PUBLIC_SITE_ASSETS_BUCKET && <p className="text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-xl p-3">PNG/JPEG/WebP بحد أقصى 5MB، وICO متاح للأيقونة. SVG مرفوض لأنه غير معقّم. هذه الأصول عامة ومخصصة لهوية الموقع والدورات والشهادات فقط.</p>}
    {error && <div className="p-3 bg-red-50 border border-red-200 text-red-700 rounded-xl text-xs">{error}</div>}
    {loading ? <div className="bg-white border rounded-3xl p-10 text-center text-sm text-slate-500">جاري تحميل المكتبة...</div> : assets.length===0 ? <div className="bg-white border rounded-3xl p-10 text-center text-sm text-slate-500">لا توجد ملفات بعد.</div> : <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{assets.map((asset) => <article key={asset.id} className={`bg-white border rounded-2xl p-4 ${asset.archivedAt?'opacity-60':''}`}>
      <div className="h-36 rounded-xl bg-slate-100 flex items-center justify-center text-indigo-500 overflow-hidden">{asset.kind==='image'&&asset.resolvedUrl?<img src={asset.resolvedUrl} alt={asset.altText||asset.fileName} loading="lazy" className="w-full h-full object-contain"/>:React.cloneElement(icon(asset.kind),{className:'w-10 h-10'})}</div>
      <p className="font-bold text-sm mt-3 truncate">{asset.fileName}</p><p className="text-[11px] text-slate-500 mt-1">{asset.mimeType||asset.kind} · {formatSize(asset.sizeBytes)} · {asset.provider}</p>{asset.kind==='image'&&<p className="text-[11px] text-slate-500">{dimensions(asset)}</p>}
      {asset.kind==='image' && <div className="flex gap-1 mt-2"><input value={altDrafts[asset.id]||''} onChange={(e) => setAltDrafts({...altDrafts,[asset.id]:e.target.value})} placeholder="النص البديل" className="min-w-0 flex-1 border rounded-lg px-2 py-1.5 text-xs"/><button type="button" disabled={busy} onClick={() => void saveAlt(asset)} className="p-2 rounded-lg bg-indigo-50 text-indigo-700" aria-label="حفظ النص البديل"><Save className="w-3.5 h-3.5"/></button></div>}
      {asset.archivedAt?<button type="button" onClick={() => void restore(asset)} className="mt-3 px-3 py-2 rounded-lg bg-indigo-50 text-indigo-700 text-xs font-bold"><RotateCcw className="inline w-3.5 h-3.5 ml-1"/>استعادة</button>:<button type="button" onClick={() => void archive(asset)} className="mt-3 px-3 py-2 rounded-lg bg-slate-100 text-slate-700 text-xs font-bold"><Archive className="inline w-3.5 h-3.5 ml-1"/>أرشفة</button>}
    </article>)}</div>}
  </section>;
};
