import React, { FormEvent, useEffect, useMemo, useState } from 'react';
import { Award, Ban, RefreshCw, Save } from 'lucide-react';
import { CertificateRecord, CertificateSettings, Course } from '../../types';
import { certificateService, coursesService } from '../../services';
import { MediaImagePicker } from './MediaImagePicker';

const defaults = (courseId: string): CertificateSettings => ({ courseId, enabled: false, certificateTitle: 'شهادة إتمام الدورة', minimumFinalScore: 70, requireAllLessons: true, requireFinalQuiz: true, templateSettings: { layout: 'landscape', accentColor: '#4f46e5' }, signatoryName: '', signatoryTitle: '', wording: 'تشهد منصة English30 بأن المتعلم قد أتم متطلبات الدورة بنجاح.' });

export const OwnerCertificates: React.FC = () => {
  const [courses,setCourses] = useState<Course[]>([]); const [allSettings,setAllSettings] = useState<CertificateSettings[]>([]); const [certificates,setCertificates] = useState<CertificateRecord[]>([]); const [courseId,setCourseId] = useState(''); const [form,setForm] = useState<CertificateSettings>(defaults('')); const [busy,setBusy] = useState(false); const [error,setError] = useState(''); const [message,setMessage] = useState('');
  const load = async () => { const [courseRows,settingsRows,certificateRows] = await Promise.all([coursesService.getCourses(),certificateService.listSettings(),certificateService.listAll()]); setCourses(courseRows); setAllSettings(settingsRows); setCertificates(certificateRows); setCourseId((current) => current || courseRows[0]?.id || ''); };
  useEffect(() => { void load().catch((reason) => setError(reason.message)); }, []);
  useEffect(() => { if (!courseId) return; setForm(allSettings.find((item) => item.courseId === courseId) || defaults(courseId)); }, [courseId,allSettings]);
  const selectedCourse = useMemo(() => courses.find((course) => course.id === courseId), [courses,courseId]);
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await certificateService.saveSettings(form); setMessage('تم حفظ إعدادات الشهادة. الإصدار التلقائي يتم من قاعدة البيانات عند تحقق الشروط.'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر الحفظ.'); } finally { setBusy(false); } };
  const revoke = async (certificate: CertificateRecord) => { const reason = prompt('سبب إلغاء الشهادة:'); if (!reason) return; setBusy(true); try { await certificateService.revoke(certificate.id,reason); await load(); } catch (value) { setError(value instanceof Error ? value.message : 'تعذر الإلغاء.'); } finally { setBusy(false); } };
  const reissue = async (certificate: CertificateRecord) => { if (!confirm('إعادة إصدار الشهادة برقم ورمز تحقق جديدين؟')) return; setBusy(true); try { await certificateService.reissue(certificate.id); await load(); } catch (value) { setError(value instanceof Error ? value.message : 'تعذر إعادة الإصدار.'); } finally { setBusy(false); } };
  const logoUrl = String(form.templateSettings.logoUrl || ''); const signatureUrl = String(form.templateSettings.signatureUrl || '');

  return <section className="space-y-6" dir="rtl">
    <div><h2 className="text-2xl font-black">الشهادات التلقائية</h2><p className="text-sm text-slate-500 mt-1">شروط الإكمال والإصدار والتحقق والإلغاء تُنفذ داخل قاعدة البيانات، وليس اعتمادًا على المتصفح.</p></div>
    {error && <div className="p-4 bg-red-50 border text-red-700 rounded-2xl text-sm">{error}</div>}{message && <div className="p-4 bg-emerald-50 border text-emerald-700 rounded-2xl text-sm">{message}</div>}
    <form onSubmit={save} className="bg-white border rounded-3xl p-6 space-y-4">
      <div className="flex justify-between"><h3 className="font-black flex gap-2"><Award className="w-5 h-5 text-amber-500"/>إعداد دورة</h3><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm({...form,enabled:e.target.checked})}/>إصدار الشهادات</label></div>
      <select value={courseId} onChange={(e) => setCourseId(e.target.value)} className="w-full border rounded-xl p-3 text-sm">{courses.map((course) => <option key={course.id} value={course.id}>{course.titleAr}</option>)}</select>
      <div className="grid md:grid-cols-2 gap-3"><input value={form.certificateTitle} onChange={(e) => setForm({...form,certificateTitle:e.target.value})} placeholder="عنوان الشهادة" className="border rounded-xl p-3 text-sm"/><label className="text-xs font-bold">الحد الأدنى للنتيجة<input type="number" min="0" max="100" value={form.minimumFinalScore} onChange={(e) => setForm({...form,minimumFinalScore:Number(e.target.value)})} className="mt-1 w-full border rounded-xl p-3 text-sm"/></label><input value={form.signatoryName||''} onChange={(e) => setForm({...form,signatoryName:e.target.value})} placeholder="اسم الموقّع" className="border rounded-xl p-3 text-sm"/><input value={form.signatoryTitle||''} onChange={(e) => setForm({...form,signatoryTitle:e.target.value})} placeholder="صفة الموقّع" className="border rounded-xl p-3 text-sm"/></div>
      <div className="grid lg:grid-cols-2 gap-4">
        <MediaImagePicker label="شعار الشهادة" valueUrl={logoUrl} valueAssetId={form.logoAssetId} folder="certificates" onChange={(selected) => setForm({...form,logoAssetId:selected?.assetId,templateSettings:{...form.templateSettings,logoUrl:selected?.url}})}/>
        <MediaImagePicker label="صورة التوقيع" valueUrl={signatureUrl} valueAssetId={form.signatureAssetId} folder="certificates" onChange={(selected) => setForm({...form,signatureAssetId:selected?.assetId,templateSettings:{...form.templateSettings,signatureUrl:selected?.url}})}/>
      </div>
      <label className="text-xs font-bold block">لون القالب<input type="color" value={String(form.templateSettings.accentColor||'#4f46e5')} onChange={(e) => setForm({...form,templateSettings:{...form.templateSettings,accentColor:e.target.value,layout:'landscape'}})} className="mt-1 w-full h-12 border rounded-xl p-1"/></label>
      <textarea value={form.wording||''} onChange={(e) => setForm({...form,wording:e.target.value})} rows={3} placeholder="صياغة الشهادة" className="w-full border rounded-xl p-3 text-sm"/><div className="flex flex-wrap gap-4 text-xs font-bold"><label><input type="checkbox" checked={form.requireAllLessons} onChange={(e) => setForm({...form,requireAllLessons:e.target.checked})} className="ml-2"/>إكمال كل الدروس</label><label><input type="checkbox" checked={form.requireFinalQuiz} onChange={(e) => setForm({...form,requireFinalQuiz:e.target.checked})} className="ml-2"/>اجتياز الاختبار النهائي</label></div><button disabled={busy||!selectedCourse} className="px-5 py-3 bg-indigo-600 text-white rounded-xl text-sm font-black flex gap-2"><Save className="w-4 h-4"/>حفظ الإعدادات</button>
    </form>
    <div className="bg-white border rounded-3xl p-5 space-y-4"><div className="flex justify-between"><h3 className="font-black">الشهادات الصادرة</h3><button type="button" onClick={() => void load()} className="p-2 border rounded-lg"><RefreshCw className="w-4 h-4"/></button></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-right border-b"><th className="p-3">الطالب</th><th>الدورة</th><th>الرقم</th><th>الحالة</th><th>الإصدار</th><th></th></tr></thead><tbody>{certificates.map((certificate) => <tr key={certificate.id} className="border-b"><td className="p-3 font-bold">{certificate.studentName}</td><td>{certificate.courseTitle}</td><td dir="ltr">{certificate.certificateNumber}</td><td>{certificate.status}</td><td>{new Date(certificate.issuedAt).toLocaleDateString('ar-SA')}</td><td><div className="flex gap-1"><button type="button" disabled={busy||certificate.status!=='active'} onClick={() => void revoke(certificate)} className="p-2 bg-red-50 text-red-700 rounded-lg"><Ban className="w-4 h-4"/></button><button type="button" disabled={busy} onClick={() => void reissue(certificate)} className="px-3 py-2 bg-indigo-50 text-indigo-700 rounded-lg font-bold">إعادة إصدار</button></div></td></tr>)}</tbody></table></div>{certificates.length===0 && <p className="text-center text-slate-500 py-6 text-sm">لم تصدر شهادات بعد.</p>}</div>
  </section>;
};
