import React, { useEffect, useState } from 'react';
import { Clock3, RotateCcw } from 'lucide-react';
import { ContentVersion } from '../../types';
import { ownerCmsService } from '../../services';

export const OwnerContentVersions: React.FC=()=>{
  const [versions,setVersions]=useState<ContentVersion[]>([]);const [entityType,setEntityType]=useState('');const [busy,setBusy]=useState('');const [error,setError]=useState('');
  const load=async()=>setVersions(await ownerCmsService.listVersions(entityType||undefined));
  useEffect(()=>{void load().catch(reason=>setError(reason.message));},[entityType]);
  const restore=async(version:ContentVersion)=>{if(!confirm(`استعادة النسخة ${version.versionNumber}؟ ستُحفظ الحالة الحالية تلقائيًا كنسخة أخرى.`))return;setBusy(version.id);try{await ownerCmsService.restoreVersion(version.id);await load();}catch(reason){setError(reason instanceof Error?reason.message:'تعذر الاستعادة.');}finally{setBusy('');}};
  return <section className="space-y-5" dir="rtl"><div><h2 className="text-2xl font-black">سجل نسخ المحتوى</h2><p className="text-sm text-slate-500 mt-1">كل تعديل يحتفظ بالنسخة السابقة، والاستعادة لا تمحو النسخة الحالية.</p></div>{error&&<div className="p-4 bg-red-50 border text-red-700 rounded-2xl text-sm">{error}</div>}<select value={entityType} onChange={e=>setEntityType(e.target.value)} className="border bg-white rounded-xl p-3 text-sm"><option value="">كل الأنواع</option>{['courses','lessons','lesson_content','lesson_blocks','quizzes','cms_pages'].map(type=><option key={type} value={type}>{type}</option>)}</select><div className="space-y-3">{versions.map(version=><article key={version.id} className="bg-white border rounded-2xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><Clock3 className="w-4 h-4 text-indigo-600"/><h3 className="font-black text-sm">{version.entityType} · النسخة {version.versionNumber}</h3></div><p className="text-[11px] text-slate-500 mt-1" dir="ltr">{version.entityId} · {new Date(version.createdAt).toLocaleString('ar-SA')} · by {version.changedByName||version.changedBy||'system'}</p><details className="mt-2"><summary className="text-xs text-indigo-700 cursor-pointer">عرض البيانات المحفوظة</summary><pre className="mt-2 max-h-52 overflow-auto bg-slate-950 text-slate-100 rounded-xl p-3 text-[10px] text-left" dir="ltr">{JSON.stringify(version.snapshot,null,2)}</pre></details></div><button disabled={busy===version.id} onClick={()=>void restore(version)} className="px-4 py-2 bg-indigo-50 text-indigo-700 rounded-xl text-xs font-black flex gap-2 self-start"><RotateCcw className="w-4 h-4"/>استعادة</button></article>)}</div>{versions.length===0&&<div className="bg-white border rounded-3xl p-10 text-center text-sm text-slate-500">لا توجد نسخ سابقة بعد.</div>}</section>;
};
