import React, { useEffect, useState } from 'react';
import { ActiveTab, Lesson, VocabItem, SentenceItem, FillInBlankQuestion, QuizQuestion } from '../types';
import { lessonsService } from '../services';
import { playAudioItem } from '../lib/speech';
import confetti from 'canvas-confetti';
import { Volume2, CheckCircle2, XCircle, HelpCircle, ArrowRight, Sparkles, BookOpen, Award, ChevronLeft, ChevronRight, MessageCircle, Check, RefreshCw, Video, Play, Pause, Clock, Film, Subtitles, List } from 'lucide-react';

interface LessonViewProps { lesson?: Lesson; setActiveTab: (tab: ActiveTab) => void; onLessonCompleted: (xpEarned: number) => void; }

export const LessonView: React.FC<LessonViewProps> = ({ lesson: providedLesson, setActiveTab, onLessonCompleted }) => {
  const [lesson, setLesson] = useState<Lesson | null>(providedLesson ?? null);
  const [loading, setLoading] = useState(!providedLesson);
  const [loadError, setLoadError] = useState('');
  const [activeLessonStep, setActiveLessonStep] = useState<'explanation'|'video'|'vocab'|'sentences'|'grammar'|'fill-blank'|'quiz'|'final-test'|'completed'>('explanation');
  const [isPlayingVideo, setIsPlayingVideo] = useState(false); const [videoSpeed, setVideoSpeed] = useState(1); const [showSubtitles, setShowSubtitles] = useState(true); const [speakingId, setSpeakingId] = useState<string|null>(null);
  const [fibAnswers, setFibAnswers] = useState<Record<string,string>>({}); const [showFibResults, setShowFibResults] = useState(false); const [selectedAnswers, setSelectedAnswers] = useState<Record<string,number>>({}); const [showQuizResults, setShowQuizResults] = useState(false); const [finalAnswers, setFinalAnswers] = useState<Record<string,number>>({}); const [showFinalResults, setShowFinalResults] = useState(false);

  useEffect(() => { if (providedLesson) { setLesson(providedLesson); setLoading(false); return; } let mounted=true; const load=async()=>{setLoading(true);try{const data=await lessonsService.getLessons(undefined,'published');if(mounted)setLesson(data[0]??null);}catch(e){if(mounted)setLoadError(e instanceof Error?e.message:'تعذر تحميل الدرس.');}finally{if(mounted)setLoading(false);}};void load();return()=>{mounted=false;}; }, [providedLesson]);
  const handlePlayAudio=async(text:string,id:string,slow=false)=>{setSpeakingId(id);await playAudioItem(text,undefined,slow);setSpeakingId(null);};
  const handleSelectQuizAnswer=(id:string,index:number)=>{if(!showQuizResults)setSelectedAnswers(p=>({...p,[id]:index}));};
  const handleSelectFinalAnswer=(id:string,index:number)=>{if(!showFinalResults)setFinalAnswers(p=>({...p,[id]:index}));};
  const handleFinishLesson=()=>{confetti({particleCount:120,spread:70,origin:{y:.6}});onLessonCompleted(100);setActiveLessonStep('completed');};
  if(loading)return <div className="max-w-4xl mx-auto py-20 text-center text-sm text-slate-500">جاري تحميل الدرس...</div>;
  if(loadError)return <div className="max-w-4xl mx-auto py-20 text-center"><div className="bg-red-50 text-red-700 p-5 rounded-2xl">{loadError}</div></div>;
  if(!lesson)return <div className="max-w-4xl mx-auto py-20 text-center space-y-4"><div className="text-5xl">📚</div><h2 className="text-xl font-black">لا يوجد درس منشور بعد</h2><p className="text-sm text-slate-500">يمكنك إنشاء الدروس من لوحة المالك.</p><button onClick={()=>setActiveTab('courses')} className="bg-indigo-600 text-white px-5 py-3 rounded-xl text-sm font-bold">استعراض الدورات</button></div>;
  const calculateQuizScore=()=>lesson.quizQuestions.reduce((s,q)=>s+(selectedAnswers[q.id]===q.correctAnswerIndex?1:0),0);
  const calculateFinalTestScore=()=>lesson.finalMiniTest?.questions?.reduce((s,q)=>s+(finalAnswers[q.id]===q.correctAnswerIndex?1:0),0)??0;
  return <div className="max-w-4xl mx-auto space-y-8 py-6" dir="rtl">
    <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-xs space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><button onClick={()=>setActiveTab('courses')} className="flex items-center gap-1 text-xs font-bold text-slate-500 hover:text-slate-800"><ArrowRight className="w-4 h-4"/>العودة للدورات</button><div className="flex items-center gap-2 text-xs font-bold"><span className="px-3 py-1 bg-indigo-50 text-indigo-700 rounded-full">مستوى {lesson.level}</span><span className="px-3 py-1 bg-slate-100 text-slate-700 rounded-full">الوحدة {lesson.unitNumber}</span><span className="text-slate-500">⏱️ {lesson.durationMinutes} دقيقة</span></div></div><h1 className="text-2xl sm:text-3xl font-black text-slate-900">{lesson.titleAr}</h1><p className="text-sm font-semibold text-slate-500 font-english">{lesson.titleEn}</p><div className="flex items-center gap-1.5 overflow-x-auto pb-1 pt-2 border-t border-slate-100 text-xs font-bold">{(['explanation','video','vocab','sentences','grammar','fill-blank','quiz','final-test'] as const).map(step=><button key={step} onClick={()=>setActiveLessonStep(step)} className={`px-3.5 py-2 rounded-xl shrink-0 ${activeLessonStep===step?'bg-slate-900 text-white':'bg-slate-100 text-slate-600'}`}>{({explanation:'📖 الشرح',video:'🎬 الفيديو',vocab:`🔤 المفردات (${lesson.vocabList.length})`,sentences:'💬 الجمل',grammar:'📐 القاعدة','fill-blank':'✍️ التدريب',quiz:`📝 الاختبار (${lesson.quizQuestions.length})`,'final-test':'🏆 الاختبار النهائي'} as Record<string,string>)[step]}</button>)}</div></div>
    {activeLessonStep==='explanation'&&<section className="bg-white p-7 rounded-3xl border border-slate-200 space-y-5"><h2 className="text-xl font-black">شرح الدرس</h2><p className="text-slate-700 leading-8">{lesson.summaryAr}</p><div className="bg-indigo-50 border border-indigo-100 p-5 rounded-2xl"><h3 className="font-black text-indigo-900 mb-2">الشرح بالعربية</h3><p className="text-sm text-indigo-900/80 leading-7">{lesson.arabicExplanation||'لم تتم إضافة الشرح بعد.'}</p></div><button onClick={()=>setActiveLessonStep('video')} className="bg-indigo-600 text-white px-5 py-3 rounded-xl font-bold text-sm">ابدأ الدرس</button></section>}
    {activeLessonStep==='video'&&<section className="bg-slate-950 rounded-3xl overflow-hidden border border-slate-800"><div className="aspect-video flex items-center justify-center bg-slate-900 text-white">{lesson.videoUrl?<video controls src={lesson.videoUrl} className="w-full h-full"/>:<div className="text-center space-y-3"><Film className="w-12 h-12 mx-auto text-indigo-400"/><p className="font-bold">لم يُرفع فيديو لهذا الدرس بعد</p><p className="text-xs text-slate-400">يمكن للمالك رفع الفيديو من لوحة التحكم.</p></div>}</div></section>}
    {activeLessonStep==='vocab'&&<section className="grid sm:grid-cols-2 gap-4">{lesson.vocabList.map((v:VocabItem,i)=><article key={i} className="bg-white p-5 rounded-2xl border border-slate-200"><div className="flex items-center justify-between"><strong className="font-english text-lg">{v.word}</strong><button onClick={()=>void handlePlayAudio(v.word,`v-${i}`)} className="p-2 rounded-lg bg-indigo-50 text-indigo-700"><Volume2 className="w-4 h-4"/></button></div><p className="text-sm text-slate-600 mt-2">{v.meaning}</p><p className="text-xs text-slate-500 mt-2 font-english">{v.example}</p></article>)}</section>}
    {activeLessonStep==='sentences'&&<section className="bg-white p-7 rounded-3xl border border-slate-200 space-y-3">{lesson.sentencesList.map((s:SentenceItem,i)=><div key={i} className="p-4 bg-slate-50 rounded-xl font-english">{typeof s==='string'?s:s.sentenceEn}</div>)}</section>}
    {activeLessonStep==='grammar'&&<section className="bg-white p-7 rounded-3xl border border-slate-200 space-y-3"><h2 className="text-xl font-black">القاعدة</h2>{lesson.grammarRules.map((g:any,i)=><div key={i} className="p-4 bg-indigo-50 rounded-xl text-sm">{typeof g==='string'?g:g.ruleAr}</div>)}</section>}
    {activeLessonStep==='fill-blank'&&<section className="bg-white p-7 rounded-3xl border border-slate-200 space-y-4"><h2 className="text-xl font-black">التدريب</h2>{lesson.fillInBlankQuestions.map((q:FillInBlankQuestion,i)=><div key={i} className="p-4 border rounded-xl"><p className="font-english">{q.question}</p><input value={fibAnswers[q.id]??''} onChange={e=>setFibAnswers(p=>({...p,[q.id]:e.target.value}))} className="mt-3 border rounded-lg px-3 py-2"/><p className="text-xs text-slate-500 mt-2">{showFibResults?`الإجابة: ${q.answer}`:''}</p></div>)}<button onClick={()=>setShowFibResults(true)} className="bg-indigo-600 text-white px-5 py-3 rounded-xl font-bold">تحقق من الإجابات</button></section>}
    {activeLessonStep==='quiz'&&<section className="bg-white p-7 rounded-3xl border border-slate-200 space-y-5"><h2 className="text-xl font-black">اختبار الدرس</h2>{lesson.quizQuestions.map((q:QuizQuestion,i)=><div key={q.id} className="space-y-2"><p className="font-bold">{i+1}. {q.question}</p>{q.options.map((o:string,j:number)=><button key={j} onClick={()=>handleSelectQuizAnswer(q.id,j)} className={`block w-full text-right p-3 rounded-xl border text-sm ${selectedAnswers[q.id]===j?'border-indigo-600 bg-indigo-50':''}`}>{o}</button>)}</div>)}<button onClick={()=>setShowQuizResults(true)} className="bg-indigo-600 text-white px-5 py-3 rounded-xl font-bold">إظهار النتيجة ({calculateQuizScore()}/{lesson.quizQuestions.length})</button></section>}
    {activeLessonStep==='final-test'&&<section className="bg-white p-7 rounded-3xl border border-slate-200 space-y-5"><h2 className="text-xl font-black">الاختبار النهائي</h2>{lesson.finalMiniTest?.questions?.map((q:any,i:number)=><div key={q.id} className="space-y-2"><p className="font-bold">{i+1}. {q.question}</p>{q.options.map((o:string,j:number)=><button key={j} onClick={()=>handleSelectFinalAnswer(q.id,j)} className={`block w-full text-right p-3 rounded-xl border text-sm ${finalAnswers[q.id]===j?'border-indigo-600 bg-indigo-50':''}`}>{o}</button>)}</div>)}<button onClick={handleFinishLesson} className="bg-emerald-600 text-white px-5 py-3 rounded-xl font-bold">إنهاء الدرس ({calculateFinalTestScore()}/{lesson.finalMiniTest?.questions?.length??0})</button></section>}
    {activeLessonStep==='completed'&&<section className="bg-white p-10 rounded-3xl border text-center space-y-4"><CheckCircle2 className="w-16 h-16 mx-auto text-emerald-500"/><h2 className="text-2xl font-black">أحسنت! أكملت الدرس</h2><p className="text-slate-500">تم تسجيل إكمال الدرس في جلسة التجربة الحالية.</p><button onClick={()=>setActiveTab('courses')} className="bg-indigo-600 text-white px-5 py-3 rounded-xl font-bold">العودة للدورات</button></section>}
  </div>;
};
